name = "Magic: The Gathering"
code = "magic"
version = "0.1.0"

[[symbols]]
name="white"
path="scryfall/W.svg"
ligature="{W}"

[[symbols]]
name="blue"
path="scryfall/U.svg"
ligature="{U}"

[[symbols]]
name="black"
path="scryfall/B.svg"
ligature="{B}"

[[symbols]]
name="red"
path="scryfall/R.svg"
ligature="{R}"

[[symbols]]
name="green"
path="scryfall/G.svg"
ligature="{G}"

[[symbols]]
name="colorless"
path="scryfall/C.svg"
ligature="{C}"

[[symbols]]
name="tap"
path="scryfall/T.svg"
ligature="{T}"

[[symbols]]
name="untap"
path="scryfall/Q.svg"
ligature="{Q}"

[[symbols]]
name="energy"
path="scryfall/E.svg"
ligature="{E}"

[[symbols]]
name="chaos"
path="scryfall/CHAOS.svg"
ligature="{CHAOS}"

[[symbols]]
name="planeswalker"
path="scryfall/PW.svg"
ligature="{PW}"

# 数字法术力
[[symbols]]
name="0"
path="scryfall/0.svg"
ligature="{0}"

[[symbols]]
name="1"
path="scryfall/1.svg"
ligature="{1}"

[[symbols]]
name="2"
path="scryfall/2.svg"
ligature="{2}"

[[symbols]]
name="3"
path="scryfall/3.svg"
ligature="{3}"

[[symbols]]
name="4"
path="scryfall/4.svg"
ligature="{4}"

[[symbols]]
name="5"
path="scryfall/5.svg"
ligature="{5}"

[[symbols]]
name="6"
path="scryfall/6.svg"
ligature="{6}"

[[symbols]]
name="7"
path="scryfall/7.svg"
ligature="{7}"

[[symbols]]
name="8"
path="scryfall/8.svg"
ligature="{8}"

[[symbols]]
name="9"
path="scryfall/9.svg"
ligature="{9}"

[[symbols]]
name="10"
path="scryfall/10.svg"
ligature="{10}"

[[symbols]]
name="11"
path="scryfall/11.svg"
ligature="{11}"

[[symbols]]
name="12"
path="scryfall/12.svg"
ligature="{12}"

[[symbols]]
name="13"
path="scryfall/13.svg"
ligature="{13}"

[[symbols]]
name="14"
path="scryfall/14.svg"
ligature="{14}"

[[symbols]]
name="15"
path="scryfall/15.svg"
ligature="{15}"

[[symbols]]
name="16"
path="scryfall/16.svg"
ligature="{16}"

[[symbols]]
name="17"
path="scryfall/17.svg"
ligature="{17}"

[[symbols]]
name="18"
path="scryfall/18.svg"
ligature="{18}"

[[symbols]]
name="19"
path="scryfall/19.svg"
ligature="{19}"

[[symbols]]
name="20"
path="scryfall/20.svg"
ligature="{20}"

[[symbols]]
name="100"
path="scryfall/100.svg"
ligature="{100}"

[[symbols]]
name="1000000"
path="scryfall/1000000.svg"
ligature="{1000000}"

# 混色法术力
[[symbols]]
name="white-blue"
path="scryfall/WU.svg"
ligature="{W/U}"

[[symbols]]
name="white-black"
path="scryfall/WB.svg"
ligature="{W/B}"

[[symbols]]
name="blue-black"
path="scryfall/UB.svg"
ligature="{U/B}"

[[symbols]]
name="blue-red"
path="scryfall/UR.svg"
ligature="{U/R}"

[[symbols]]
name="black-red"
path="scryfall/BR.svg"
ligature="{B/R}"

[[symbols]]
name="black-green"
path="scryfall/BG.svg"
ligature="{B/G}"

[[symbols]]
name="red-green"
path="scryfall/RG.svg"
ligature="{R/G}"

[[symbols]]
name="red-white"
path="scryfall/RW.svg"
ligature="{R/W}"

[[symbols]]
name="green-white"
path="scryfall/GW.svg"
ligature="{G/W}"

[[symbols]]
name="green-blue"
path="scryfall/GU.svg"
ligature="{G/U}"

# 费雷西亚法术力
[[symbols]]
name="white-phyrexian"
path="scryfall/WP.svg"
ligature="{W/P}"

[[symbols]]
name="blue-phyrexian"
path="scryfall/UP.svg"
ligature="{U/P}"

[[symbols]]
name="black-phyrexian"
path="scryfall/BP.svg"
ligature="{B/P}"

[[symbols]]
name="red-phyrexian"
path="scryfall/RP.svg"
ligature="{R/P}"

[[symbols]]
name="green-phyrexian"
path="scryfall/GP.svg"
ligature="{G/P}"

# 特殊符号
[[symbols]]
name="x"
path="scryfall/X.svg"
ligature="{X}"

[[symbols]]
name="y"
path="scryfall/Y.svg"
ligature="{Y}"

[[symbols]]
name="z"
path="scryfall/Z.svg"
ligature="{Z}"

[[symbols]]
name="infinity"
path="scryfall/INFINITY.svg"
ligature="{∞}"

[[symbols]]
name="half"
path="scryfall/HALF.svg"
ligature="{½}"
