name = "Magic: The Gathering"
code = "magic"
version = "1.0.2"

[[example]]
text = '<span class="magic-icon">{W}{U}{U}</span>, <span class="magic-icon">{T}</span>, Pay X <span class="magic-icon">{E}</span>: Draw X cards.'

[[example]]
text = '<span class="magic-icon">{W}{U}{U}</span>，<span class="magic-icon">{T}</span>，支付X个<span class="magic-icon">{E}</span>：抓X张牌。'

[[example]]
text = 'Planeswalkers you control have “<span class="magic-icon">[0]</span>: Proliferate” and “<span class="magic-icon">[-12]</span>: Take an extra turn after this one.”'

[[example]]
text = '由你操控的鹏洛客具有「<span class="magic-icon">[0]</span>：增殖」与「<span class="magic-icon">[-12]</span>：于本回合后进行额外的一个回合。」'

[[categories]]
name = "normal-mana"
display_name = "基础法术力"

[[categories]]
name = "number-mana"
display_name = "数字法术力"

[[categories]]
name = "hybrid-mana"
display_name = "混血法术力"

[[categories]]
name = "phyrexian-mana"
display_name = "非瑞法术力"

[[categories]]
name = "other"
display_name = "其他符号"

[[categories]]
name = "special"
display_name = "特殊符号"

[[categories]]
name = "loyalty"
display_name = "忠诚度"

# 基础法术力
[[symbols]]
name="white"
file="W.svg"
ligature="{W}"
category="normal-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="blue"
file="U.svg"
ligature="{U}"
category="normal-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="black"
file="B.svg"
ligature="{B}"
category="normal-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="red"
file="R.svg"
ligature="{R}"
category="normal-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="green"
file="G.svg"
ligature="{G}"
category="normal-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="colorless"
file="C.svg"
ligature="{C}"
category="normal-mana"
add-shadow=true
add-flat=true

# 数字法术力
[[symbols]]
name="0"
file="0.svg"
ligature="{0}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="1"
file="1.svg"
ligature="{1}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="2"
file="2.svg"
ligature="{2}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="3"
file="3.svg"
ligature="{3}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="4"
file="4.svg"
ligature="{4}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="5"
file="5.svg"
ligature="{5}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="6"
file="6.svg"
ligature="{6}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="7"
file="7.svg"
ligature="{7}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="8"
file="8.svg"
ligature="{8}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="9"
file="9.svg"
ligature="{9}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="10"
file="10.svg"
ligature="{10}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="11"
file="11.svg"
ligature="{11}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="12"
file="12.svg"
ligature="{12}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="13"
file="13.svg"
ligature="{13}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="14"
file="14.svg"
ligature="{14}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="15"
file="15.svg"
ligature="{15}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="16"
file="16.svg"
ligature="{16}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="17"
file="17.svg"
ligature="{17}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="18"
file="18.svg"
ligature="{18}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="19"
file="19.svg"
ligature="{19}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="20"
file="20.svg"
ligature="{20}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="100"
file="100.svg"
ligature="{100}"
category="number-mana"
style={ shadow = "shadow" }

[[symbols]]
name="1000000"
file="1000000.svg"
ligature="{1000000}"
category="number-mana"
overflow=true
style={ shadow = "shadow" }

[[symbols]]
name="x"
file="X.svg"
ligature="{X}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="y"
file="Y.svg"
ligature="{Y}"
category="number-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="z"
file="Z.svg"
ligature="{Z}"
category="number-mana"
add-shadow=true
add-flat=true

# 混色法术力
[[symbols]]
name="white-blue"
file="WU.svg"
ligature="{W/U}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "white_up", "blue_down"]

[[symbols]]
name="white-black"
file="WB.svg"
ligature="{W/B}"
category="hybrid-mana"
style={ flat="flat" }
add-shadow=true
add-flat=["flat_split", "white_up", "black_down"]

[[symbols]]
name="blue-black"
file="UB.svg"
ligature="{U/B}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "blue_up", "black_down"]

[[symbols]]
name="blue-red"
file="UR.svg"
ligature="{U/R}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "blue_up", "red_down"]

[[symbols]]
name="black-red"
file="BR.svg"
ligature="{B/R}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "black_up", "red_down"]

[[symbols]]
name="black-green"
file="BG.svg"
ligature="{B/G}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "black_up", "green_down"]

[[symbols]]
name="red-green"
file="RG.svg"
ligature="{R/G}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "red_up", "green_down"]

[[symbols]]
name="red-white"
file="RW.svg"
ligature="{R/W}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "red_up", "white_down"]

[[symbols]]
name="green-white"
file="GW.svg"
ligature="{G/W}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "green_up", "white_down"]

[[symbols]]
name="green-blue"
file="GU.svg"
ligature="{G/U}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "green_up", "blue_down"]

[[symbols]]
name="two-or-white"
file="2W.svg"
ligature="{2/W}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "two_up", "white_down"]

[[symbols]]
name="two-or-blue"
file="2U.svg"
ligature="{2/U}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "two_up", "blue_down"]

[[symbols]]
name="two-or-black"
file="2B.svg"
ligature="{2/B}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "two_up", "black_down"]

[[symbols]]
name="two-or-red"
file="2R.svg"
ligature="{2/R}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "two_up", "red_down"]

[[symbols]]
name="two-or-green"
file="2G.svg"
ligature="{2/G}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "two_up", "green_down"]

[[symbols]]
name="colorless-or-white"
file="CW.svg"
ligature="{C/W}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "colorless_up", "white_down"]

[[symbols]]
name="colorless-or-blue"
file="CU.svg"
ligature="{C/U}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "colorless_up", "blue_down"]

[[symbols]]
name="colorless-or-black"
file="CB.svg"
ligature="{C/B}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "colorless_up", "black_down"]

[[symbols]]
name="colorless-or-red"
file="CR.svg"
ligature="{C/R}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "colorless_up", "red_down"]

[[symbols]]
name="colorless-or-green"
file="CG.svg"
ligature="{C/G}"
category="hybrid-mana"
add-shadow=true
add-flat=["flat_split", "colorless_up", "green_down"]

# 非瑞法术力
[[symbols]]
name="white-phyrexian"
file="WP.svg"
ligature="{W/P}"
category="phyrexian-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="blue-phyrexian"
file="UP.svg"
ligature="{U/P}"
category="phyrexian-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="black-phyrexian"
file="BP.svg"
ligature="{B/P}"
category="phyrexian-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="red-phyrexian"
file="RP.svg"
ligature="{R/P}"
category="phyrexian-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="green-phyrexian"
file="GP.svg"
ligature="{G/P}"
category="phyrexian-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="colorless-phyrexian"
file="CP.svg"
ligature="{C/P}"
category="phyrexian-mana"
add-shadow=true
add-flat=true

[[symbols]]
name="white-blue-phyrexian"
file="WUP.svg"
ligature="{W/U/P}"
category="phyrexian-mana"
add-shadow=true

[[symbols]]
name="white-black-phyrexian"
file="WBP.svg"
ligature="{W/B/P}"
category="phyrexian-mana"
add-shadow=true

[[symbols]]
name="blue-black-phyrexian"
file="UBP.svg"
ligature="{U/B/P}"
category="phyrexian-mana"
add-shadow=true

[[symbols]]
name="blue-red-phyrexian"
file="URP.svg"
ligature="{U/R/P}"
category="phyrexian-mana"
add-shadow=true

[[symbols]]
name="black-red-phyrexian"
file="BRP.svg"
ligature="{B/R/P}"
category="phyrexian-mana"
add-shadow=true

[[symbols]]
name="black-green-phyrexian"
file="BGP.svg"
ligature="{B/G/P}"
category="phyrexian-mana"
add-shadow=true

[[symbols]]
name="red-green-phyrexian"
file="RGP.svg"
ligature="{R/G/P}"
category="phyrexian-mana"
add-shadow=true

[[symbols]]
name="red-white-phyrexian"
file="RWP.svg"
ligature="{R/W/P}"
category="phyrexian-mana"
add-shadow=true

[[symbols]]
name="green-white-phyrexian"
file="GWP.svg"
ligature="{G/W/P}"
category="phyrexian-mana"
add-shadow=true

[[symbols]]
name="green-blue-phyrexian"
file="GUP.svg"
ligature="{G/U/P}"
category="phyrexian-mana"
add-shadow=true

# 其他符号
[[symbols]]
name="tap"
file="T.svg"
ligature="{T}"
category="other"
add-flat=true

[[symbols]]
name="untap"
file="Q.svg"
ligature="{Q}"
category="other"

[[symbols]]
name="snow"
file="S.svg"
ligature="{S}"
category="other"
style={ flat = "flat" }
add-shadow=true

[[symbols]]
name="energy"
file="E.svg"
ligature="{E}"
category="other"

[[symbols]]
name="phyrexian"
file="H.svg"
ligature="{H}"
category="other"

[[symbols]]
name="ticket"
file="TK.svg"
ligature="{TK}"
category="other"

[[symbols]]
name="paw"
file="P.svg"
ligature="{P}"
category="other"

# 特殊符号
[[symbols]]
name="acorn"
file="A.svg"
ligature="{A}"
category="special"

[[symbols]]
name="infinity"
file="INFINITY.svg"
ligature=["{∞}", "{INF}"]
category="special"
add-shadow=true

[[symbols]]
name="half"
file="HALF.svg"
ligature=["{½}", "{H1}", "{1/2}"]
category="special"
add-shadow=true

[[symbols]]
name="half-white"
file="HW.svg"
ligature="{HW}"
category="special"
style={ shadow = "shadow" }

[[symbols]]
name="half-red"
file="HR.svg"
ligature="{HR}"
category="special"
style={ shadow = "shadow" }

[[symbols]]
name="chaos"
file="CHAOS.svg"
ligature="{CHAOS}"
category="special"

[[symbols]]
name="planeswalker"
file="PW.svg"
ligature="{PW}"
category="special"

[[symbols]]
name="land-drop"
file="D.svg"
ligature="{D}"
category="special"

[[symbols]]
name="legendary-mana"
file="L.svg"
ligature="{L}"
category="special"

# 忠诚度
[[symbols]]
name="loyalty-0"
file="loyalty_0.svg"
ligature="[0]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+1"
file="loyalty_plus_1.svg"
ligature="[+1]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+2"
file="loyalty_plus_2.svg"
ligature="[+2]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+3"
file="loyalty_plus_3.svg"
ligature="[+3]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+4"
file="loyalty_plus_4.svg"
ligature="[+4]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+5"
file="loyalty_plus_5.svg"
ligature="[+5]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+6"
file="loyalty_plus_6.svg"
ligature="[+6]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+7"
file="loyalty_plus_7.svg"
ligature="[+7]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+8"
file="loyalty_plus_8.svg"
ligature="[+8]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+9"
file="loyalty_plus_9.svg"
ligature="[+9]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty+X"
file="loyalty_plus_X.svg"
ligature="[+X]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-1"
file="loyalty_minus_1.svg"
ligature="[-1]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-2"
file="loyalty_minus_2.svg"
ligature="[-2]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-3"
file="loyalty_minus_3.svg"
ligature="[-3]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-4"
file="loyalty_minus_4.svg"
ligature="[-4]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-5"
file="loyalty_minus_5.svg"
ligature="[-5]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-6"
file="loyalty_minus_6.svg"
ligature="[-6]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-7"
file="loyalty_minus_7.svg"
ligature="[-7]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-8"
file="loyalty_minus_8.svg"
ligature="[-8]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-9"
file="loyalty_minus_9.svg"
ligature="[-9]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-10"
file="loyalty_minus_10.svg"
ligature="[-10]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-11"
file="loyalty_minus_11.svg"
ligature="[-11]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-12"
file="loyalty_minus_12.svg"
ligature="[-12]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-13"
file="loyalty_minus_13.svg"
ligature="[-13]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-14"
file="loyalty_minus_14.svg"
ligature="[-14]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-15"
file="loyalty_minus_15.svg"
ligature="[-15]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-25"
file="loyalty_minus_25.svg"
ligature="[-25]"
category="loyalty"
create-loyalty=true

[[symbols]]
name="loyalty-X"
file="loyalty_minus_X.svg"
ligature="[-X]"
category="loyalty"
create-loyalty=true
