name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  # Allow manual workflow triggers
  workflow_dispatch:

# Set GITHUB_TOKEN permissions
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          echo "VIRTUAL_ENV=$(pwd)/.venv" >> $GITHUB_ENV
          echo "$(pwd)/.venv/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fonttools nanoemoji toml brotli

      - name: Build font and CSS
        run: python scripts/build.py

      - name: Prepare demo for GitHub Pages
        run: |
          mkdir -p public
          cp -r dist/* public/
          cp -r demo/* public/
          # Copy CNAME file for custom domain
          cp CNAME public/
          # Update reference paths in demo
          sed -i 's|\.\./dist/|./|g' public/index.html
          # Update JSON path in JavaScript file
          sed -i 's|\.\./dist/|./|g' public/script.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
